### PR TITLE
Push notifications

### PR DESCRIPTION
**Pull request by yaroslavr-itd**
Added table with user notification tokens.
Added routes and logic for marking tokens as active/inactive.

### CODE REVIEW

**Comment by israellevin** [comment]
@yaroslavr-itd , why do we have notification code here? When does funder send notifications? I think that only router should send notifications...

**Comment by yaroslavr-itd** [comment]
@israellevin, mobile client should send to server info about active/inactive user tokens. It is user-relative thing. And in funder we have all user-related things. So, I've decided to place it here. 
And, of course, in future we may send notifications related to funder. For example, we can send notifications during funding new users with starting BULs.

**Comment by israellevin** [comment]
@yaroslavr-itd: Hmmm... I really think we should only have notifications from router. Ever. Notification about getting BUL is something you can do without a server, by checking the stellar ledger.

And the way the router manage users is by asking using keypairs and the funder api. If that does not make sense, please let me know and we will discuss it.

**Comment by yaroslavr-itd** [comment]
user tokens handling removed from funder. Branch will be deleted without merging to master.

**Pull request closed without merging**
